from __future__ import annotations

CAPABILITY_TERMS: dict[str, tuple[str, ...]] = {
    "background_remove": (
        "background remove",
        "background removal",
        "remove background",
        "remove bg",
        "foreground segmentation",
        "transparent cutout",
    ),
    "alpha_cleanup": (
        "alpha cleanup",
        "alpha mask",
        "edge cleanup",
        "fringe removal",
        "alpha hardening",
    ),
    "trim_transparent_margin": (
        "trim transparent",
        "transparent margin",
        "trim whitespace",
    ),
    "padding_normalize": (
        "padding normalize",
        "normalize padding",
        "consistent padding",
    ),
    "pixel_cleanup": (
        "pixel art cleanup",
        "pixel-art cleanup",
        "pixel cleanup",
        "pixel cleanup pipeline",
    ),
    "palette_reduce": (
        "palette reduce",
        "palette reduction",
        "reduce colors",
        "color reduction",
    ),
    "palette_lock": (
        "palette lock",
        "fixed palette",
        "palette mapping",
        "locked palette",
    ),
    "despeckle": (
        "despeckle",
        "noise pixel removal",
        "isolated pixel removal",
    ),
    "grid_recover": (
        "grid recovery",
        "recover pixel grid",
        "pixel grid recovery",
        "grid reconstruction",
    ),
    "frame_extract": (
        "frame extraction",
        "extract frames",
        "video to frames",
        "video-to-frames",
    ),
    "frame_align": (
        "frame alignment",
        "align frames",
        "sprite alignment",
    ),
    "sprite_sheet_pack": (
        "sprite sheet",
        "spritesheet",
        "sprite atlas",
        "atlas packing",
    ),
    "animation_preview_gif": (
        "gif preview",
        "animated gif",
        "animation preview",
        "preview gif",
    ),
    "godot_export": (
        "godot export",
        "godot import",
        "godot asset",
    ),
    "unity_export": (
        "unity export",
        "unity import",
        "unity asset",
    ),
    "visual_qa": (
        "visual qa",
        "visual quality check",
        "quality inspection",
    ),
    "pixelate": (
        "pixelate",
        "pixelation",
        "true pixel art",
    ),
    "image_generate": (
        "generate game assets",
        "sprites and icons",
        "concept art",
        "key art",
    ),
    "image_edit": (
        "consistent variants",
        "recolors",
        "same character new pose",
    ),
    "image_upscale": (
        "upscale",
        "upscaling",
    ),
    "vector_edit": (
        "vector illustration",
        "vector graphics",
        "svg editing",
        "edit vector",
    ),
    "texture_generate": (
        "seamless texture",
        "seamless textures",
        "tiling texture",
        "tileable texture",
    ),
    "pbr_generate": (
        "pbr material",
        "pbr maps",
        "pbr map",
    ),
    "model3d_generate": (
        "image-to-3d",
        "image → textured 3d model",
        "image to 3d",
    ),
    "rig_generate": (
        "auto-rig",
        "auto-rigging",
        "rigging",
    ),
    "sfx_generate": (
        "`um fal sfx`",
        "sound effects",
    ),
    "music_generate": (
        "`um fal music`",
        "music generation",
    ),
    "voice_generate": (
        "`um fal voice`",
        "voice lines",
    ),
    "video_generate": (
        "`um fal video`",
        "cutscene video",
        "trailer or cutscene video",
    ),
    "sprite_cutout": (
        "sprite cutout",
        "sprite cut out",
        "cutout sprite",
    ),
    "sprite_fit": (
        "nearest-neighbour fit",
        "nearest-neighbour fitting",
        "sprite fit",
    ),
    "render3d_to_sprite": (
        "3d → sprites",
        "3d model into sprite frames",
        "3d-to-sprite",
    ),
    "video_edit": (
        "showcase video",
        "video compile",
        "edl json",
    ),
    "image_to_mesh": (
        "single-image 3d reconstruction",
        "single image to 3d",
        "image-to-mesh",
        "image to mesh",
        "image-to-3d",
        "image to 3d",
    ),
    "mesh_texture_bake": (
        "texture bake",
        "texture baking",
        "bake textures",
        "textured mesh",
    ),
    "uv_unwrap": (
        "uv unwrap",
        "uv unwrapping",
        "automatic uv",
    ),
    "material_predict": (
        "material prediction",
        "material parameters",
        "metallic roughness",
    ),
    "image_delight": (
        "delighting",
        "de-lighting",
        "illumination removal",
        "remove illumination",
    ),
    "mesh_decimate": (
        "mesh decimation",
        "mesh simplify",
        "mesh simplification",
    ),
    "mesh_repair": (
        "mesh repair",
        "repair mesh",
        "mesh cleanup",
    ),
    "mesh_qa": (
        "mesh qa",
        "mesh quality",
        "mesh validation",
    ),
    "glb_export": (
        "glb export",
        "export glb",
        "gltf export",
        "export gltf",
    ),
    "vfx_create": (
        "create effekseer effects",
        "create particle effects",
        "particle effect editing tool",
    ),
    "vfx_edit": (
        "edit effekseer effects",
        "editing particle effects",
        "edit .efkefc",
    ),
    "vfx_runtime_export": (
        "export runtime .efk",
        "runtime .efk files",
        "export effekseer runtime",
    ),
    "vfx_runtime_playback": (
        "effekseer runtime playback",
        "effects can be played back",
        "play effekseer effects",
    ),
    "vfx_resource_import": (
        "import image assets",
        "effect-local resources",
    ),
    "vfx_mcp_authoring": (
        "effekseer mcp",
        "mcp-compatible ai clients",
        "mcp server for creating and editing effekseer",
    ),
    "godot_vfx_playback": (
        "godot vfx playback",
        "effekseer effects in godot",
        "effects in godot engine 4.x",
    ),
}

CAPABILITY_IO: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "background_remove": (("image",), ("transparent_png",)),
    "alpha_cleanup": (("transparent_png",), ("transparent_png",)),
    "trim_transparent_margin": (("transparent_png",), ("transparent_png",)),
    "padding_normalize": (("transparent_png",), ("transparent_png",)),
    "pixel_cleanup": (("image",), ("pixel_art_png",)),
    "palette_reduce": (("image",), ("pixel_art_png",)),
    "palette_lock": (("image",), ("pixel_art_png",)),
    "despeckle": (("image",), ("pixel_art_png",)),
    "grid_recover": (("image",), ("pixel_art_png",)),
    "frame_extract": (("video", "sprite_sheet"), ("frames",)),
    "frame_align": (("frames",), ("frames",)),
    "sprite_sheet_pack": (("frames",), ("sprite_sheet",)),
    "animation_preview_gif": (("frames", "sprite_sheet"), ("gif",)),
    "godot_export": (("image", "sprite_sheet"), ("godot_asset",)),
    "unity_export": (("image", "sprite_sheet"), ("unity_asset",)),
    "visual_qa": (("image",), ("qa_report",)),
    "pixelate": (("image",), ("pixel_art_png",)),
    "image_generate": (("prompt",), ("image",)),
    "image_edit": (("image", "prompt"), ("image",)),
    "image_upscale": (("image",), ("image",)),
    "vector_edit": (("vector_image", "svg"), ("vector_image", "svg")),
    "texture_generate": (("prompt",), ("texture",)),
    "pbr_generate": (("prompt",), ("pbr_material_set",)),
    "model3d_generate": (("image",), ("model_3d",)),
    "rig_generate": (("model_3d",), ("rigged_model_3d",)),
    "sfx_generate": (("prompt",), ("audio",)),
    "music_generate": (("prompt",), ("audio",)),
    "voice_generate": (("text",), ("audio",)),
    "video_generate": (("image", "prompt"), ("video",)),
    "sprite_cutout": (("image",), ("transparent_png",)),
    "sprite_fit": (("image",), ("sprite_frame",)),
    "render3d_to_sprite": (("model_3d",), ("frames",)),
    "video_edit": (("video",), ("video",)),
    "image_to_mesh": (("image",), ("model_3d",)),
    "mesh_texture_bake": (("model_3d", "image"), ("textured_model_3d",)),
    "uv_unwrap": (("model_3d",), ("uv_model_3d",)),
    "material_predict": (("model_3d", "image"), ("material_params",)),
    "image_delight": (("image",), ("delighted_image",)),
    "mesh_decimate": (("model_3d",), ("model_3d",)),
    "mesh_repair": (("model_3d",), ("model_3d",)),
    "mesh_qa": (("model_3d",), ("qa_report",)),
    "glb_export": (("model_3d",), ("glb",)),
    "vfx_create": (("vfx_brief", "image"), ("effekseer_effect_source",)),
    "vfx_edit": (("effekseer_effect_source",), ("effekseer_effect_source",)),
    "vfx_runtime_export": (("effekseer_effect_source",), ("effekseer_runtime_effect",)),
    "vfx_runtime_playback": (("effekseer_runtime_effect",), ("vfx_playback",)),
    "vfx_resource_import": (("image", "effekseer_effect_source"), ("effekseer_effect_source",)),
    "vfx_mcp_authoring": (("vfx_brief", "effekseer_effect_source"), ("effekseer_effect_source",)),
    "godot_vfx_playback": (("effekseer_runtime_effect",), ("godot_vfx_playback",)),

}
